<?php

namespace AppBundle\Repository;

/**
 * WaypointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaypointRepository extends \Doctrine\ORM\EntityRepository
{
}
